language: php
php:
  - "5.5"
  - "5.4"
  - hhvm
env:
  - MUNITION_ENV=test

before_install:
  - mysql < tests/sql_fixture.sql
  
before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit
after_script:
 - php vendor/bin/coveralls -v

services:
  - mysql